INSERT into City values(1,'Mumbai');
INSERT into City values(2,'PUNE');
INSERT into City values(3,'Bengluru');
INSERT into City values(4,'BHOPAL');
INSERT into EMPLOYEE values(101,'kamran8797@yahoo.in','kamran','male','8818936545',0);
INSERT into EMPLOYEE values(102,'kamran8797@gmail.in','khan','male','8818939898',1);
INSERT into Address values(1001,'Government office Address 1','Government',1,101);
INSERT into Address values(1002,'Private office Address 1','Private',2,102);
INSERT into Office_address values(1,'Government','Government office Address 1');
INSERT into Office_address values(2,'Government','Government office Address 2');
INSERT into office_address values(3,'Private','Private office Address 1');
INSERT into office_address values(4,'Private','Private office Address 2');